<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  '' => 
  array (
    'package' => 'ksf_FA_ImportStagingProcessing',
    'name' => 'ksf_FA_ImportStagingProcessing',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_FA_ImportStagingProcessing',
    'active' => false,
  ),
  1 => 
  array (
    'package' => 'FA_ProductAttributes',
    'name' => 'FA_ProductAttributes',
    'version' => '2.4.4',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/FA_ProductAttributes',
    'active' => true,
  ),
  2 => 
  array (
    'package' => 'export_woocommerce',
    'name' => 'export_woocommerce',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/export_woocommerce',
    'active' => false,
  ),
  3 => 
  array (
    'package' => 'ksf_Calendar',
    'name' => 'ksf_Calendar',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_Calendar',
    'active' => false,
  ),
  4 => 
  array (
    'package' => 'ksf_FA_Common',
    'name' => 'ksf_FA_Common',
    'version' => '2.4.4',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_FA_Common',
    'active' => true,
  ),
  5 => 
  array (
    'package' => 'ksf_FA_CRM',
    'name' => 'ksf_FA_CRM',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_FA_CRM',
    'active' => false,
  ),
  6 => 
  array (
    'package' => 'ksf_FA_DataIntegrity',
    'name' => 'ksf_FA_DataIntegrity',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_FA_DataIntegrity',
    'active' => false,
  ),
  7 => 
  array (
    'package' => 'ksf_FA_HRM',
    'name' => 'ksf_FA_HRM',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_FA_HRM',
    'active' => false,
  ),
);
