<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  '' => 
  array (
    'package' => 'ksf_FA_API',
    'name' => 'ksf_FA_API',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_FA_API',
    'active' => false,
  ),
  1 => 
  array (
    'package' => 'ksf_FA_Calendar',
    'name' => 'ksf_FA_Calendar',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_FA_Calendar',
    'active' => false,
  ),
);
