<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  '' =>
  array (
    'package' => 'ksf_FA_API',
    'name' => 'ksf_FA_API',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_FA_API',
    'active' => true,
  ),
  1 =>
  array (
    'package' => 'ksf_FA_Calendar',
    'name' => 'ksf_FA_Calendar',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_FA_Calendar',
    'active' => true,
  ),
  2 =>
  array (
    'package' => 'ksf_FA_RBAC',
    'name' => 'ksf_FA_RBAC',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_FA_RBAC',
    'active' => true,
  ),
  3 =>
  array (
    'package' => 'ksf_FA_CRM',
    'name' => 'ksf_FA_CRM',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_FA_CRM',
    'active' => true,
  ),
  4 =>
  array (
    'package' => 'ksf_FA_Mail',
    'name' => 'ksf_FA_Mail',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_FA_Mail',
    'active' => true,
  ),
);
